[no-cd]
default:
    # Populate file_list.txt via create_file_list.py or manual URLs first
    uv run python source_download.py nonna
    uv run python source_unzip.py nonna
    uv run python source_bounds.py nonna
    uv run python source_polygonize.py nonna 32
    uv run python source_create_tarball.py nonna
