[no-cd]
default:
    cd ../source-catalog/bluetopo && python3 create_file_list.py
    uv run python source_download.py bluetopo
    uv run python source_bluetopo_extract.py bluetopo
    uv run python source_bounds.py bluetopo
    uv run python source_polygonize.py bluetopo 32
    uv run python source_create_tarball.py bluetopo
