[no-cd]
default:
    uv run python source_download.py emodnet
    uv run python source_unzip.py emodnet
    uv run python source_bounds.py emodnet
    uv run python source_polygonize.py emodnet 32
    uv run python source_create_tarball.py emodnet
