# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py zzarcticdemc
    uv run python source_to_cog.py zzarcticdemc
    uv run python source_to_egm2008.py zzarcticdemc
    uv run python source_bounds.py zzarcticdemc
    uv run python source_polygonize.py zzarcticdemc 32
    uv run python source_create_tarball.py zzarcticdemc
