# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_get_file_list.py nl50cm
    uv run python source_download.py nl50cm
    # fill holes
    uv run python source_fill_nodata.py nl50cm
    uv run python source_to_cog.py nl50cm
    uv run python source_bounds.py nl50cm
    # also fix compound CRS EPSG:28992
    uv run python source_polygonize.py nl50cm 32 EPSG:28992
    uv run python source_create_tarball.py nl50cm