[no-cd]
default:
    uv run python source_download.py debug-gebco
    uv run python source_normalize_filenames.py debug-gebco
    uv run python source_bounds.py debug-gebco
    uv run python source_polygonize.py debug-gebco 32
    uv run python source_create_tarball.py debug-gebco
