# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py remac
    uv run python source_to_cog.py remac
    uv run python source_to_egm2008.py remac
    uv run python source_bounds.py remac
    uv run python source_polygonize.py remac 32
    uv run python source_create_tarball.py remac
