"""Generate download_urls.json manifest describing PMTiles bundle metadata.

This module creates the JSON manifest that clients use to discover and
download available PMTiles bundles:

**Manifest structure**:
```json
{
  "version": "2024.01.15",  // Release identifier
  "items": [
    {
      "name": "planet.pmtiles",
      "url": "https://download.mapterhorn.com/planet.pmtiles",
      "md5sum": "abc123...",
      "size": 12345678,
      "min_zoom": 0,
      "max_zoom": 12,
      "bounds": [-180, -90, 180, 90]
    },
    // Regional bundles (z=6 tiles)
    { "name": "6-32-21.pmtiles", ... }
  ]
}
```

**Metadata extraction**:
1. Enumerate bundle-store/ PMTiles (planet + regional)
2. For each bundle:
   a. Read PMTiles header via pmtiles.reader
   b. Extract min_zoom, max_zoom from header
   c. Derive tile coordinates from filename
   d. Compute geographic bounds via mercantile.bounds
   e. Read MD5 checksum from .md5 sidecar file
   f. Stat file size in bytes
3. Sort items: planet first, then regional by z-x-y
4. Write bundle-store/download_urls.json

**Client usage**:
- Download manifest to discover available bundles
- Check md5sum to verify downloads or detect updates
- Use bounds to select regional bundles for area of interest
- Use zoom range to determine coverage granularity

**Output**: JSON manifest for CDN distribution and client consumption.
"""

import os
import sys
import json

import mercantile
from pmtiles.reader import Reader, MmapSource

import bundle


def get_md5sum(filepath):
    """Read checksum from a .md5 sidecar file.

    File format (md5sum command output):
    ```
    abc123def456...  filename.pmtiles
    ```

    Parsing:
    1. Read {filepath}.md5 (e.g., planet.pmtiles.md5)
    2. Split line on spaces
    3. Extract first part (hex checksum)
    4. Validate 2-part format (checksum + filename)

    The .md5 files are generated by verify_upload.py after bundle creation,
    providing cryptographic verification for downloads.

    Args:
        filepath: PMTiles file path (without .md5 extension)

    Returns:
        str: MD5 checksum as 32-character hex string
    """
    checksum = None
    with open(f"{filepath}.md5") as f:
        line = f.readline()
        parts = line.strip().split(" ")
        assert len(parts) == 2
        checksum = parts[0]
    return checksum


def main():
    """Enumerate bundled PMTiles and emit bundle-store/download_urls.json.

    Manifest generation:
    1. Validate version argument (e.g., '2024.01.15' release tag)
    2. get_parent_to_filepaths(False): List all bundles (not just dirty)
    3. get_name_from_parent: Convert tile coords → filenames
       - (0,0,0) → 'planet.pmtiles'
       - (z,x,y) → '{z}-{x}-{y}.pmtiles'
    4. For each bundle file:
       a. Open PMTiles with Reader(MmapSource(...))
       b. Extract header: min_zoom, max_zoom
       c. Parse tile coordinates from filename
       d. mercantile.bounds: Compute geographic bbox
       e. get_md5sum: Read checksum from .md5 sidecar
       f. os.path.getsize: Get file size in bytes
       g. Build item dict with all metadata
    5. Assemble JSON structure:
       - version: From command-line arg
       - items: List of bundle metadata dicts
    6. Write to bundle-store/download_urls.json

    The version string identifies the release and appears in URLs,
    enabling clients to check for updates by comparing versions.

    Args:
        sys.argv[1]: Version string (e.g., '2024.01.15')

    Output:
        bundle-store/download_urls.json: Complete manifest for distribution
    """
    version = None
    if len(sys.argv) > 1:
        version = sys.argv[1]
        print(f"start creating download_urls.json for version {version}...")
    else:
        print("version argument missing...")
        exit()

    parent_to_filepaths = bundle.get_parent_to_filepaths(False)
    parents = parent_to_filepaths.keys()
    names = [bundle.get_name_from_parent(parent) for parent in parents]
    filepaths = [f"bundle-store/{name}/{name}.pmtiles" for name in names]

    data = {"version": version, "items": []}
    for filepath in filepaths:
        min_zoom = None
        max_zoom = None
        with open(filepath, "r+b") as f2:
            reader = Reader(MmapSource(f2))
            header = reader.header()
            min_zoom = header["min_zoom"]
            max_zoom = header["max_zoom"]
        filename = filepath.split("/")[-1]
        tile = None
        if filename == "planet.pmtiles":
            tile = mercantile.Tile(x=0, y=0, z=0)
        else:
            z, x, y = [int(a) for a in filename.replace(".pmtiles", "").split("-")]
            tile = mercantile.Tile(x=x, y=y, z=z)

        bounds = mercantile.bounds(tile)
        data["items"].append(
            {
                "name": filename,
                "url": f"https://download.mapterhorn.com/{filename}",
                "md5sum": get_md5sum(filepath),
                "size": os.path.getsize(filepath),
                "min_lon": bounds.west,
                "min_lat": bounds.south,
                "max_lon": bounds.east,
                "max_lat": bounds.north,
                "min_zoom": min_zoom,
                "max_zoom": max_zoom,
            }
        )
        print(json.dumps(data["items"][-1], indent=2))

    with open("bundle-store/download_urls.json", "w") as f:
        json.dump(data, f, indent=2)


if __name__ == "__main__":
    main()
