# Minimal required just version: 1.21.0 (Ubuntu LTS)
set dotenv-load
set shell := ["bash", "-c"]

_default:
    @just --list --unsorted

debug-sources := "debug-glo30 debug-swissalti3d"
all-sources := "glo30 swissalti3d at10 atburgenland atoberoesterreich atsalzburg atkaernten beflanders bewallon cz debayern deniedersachsen"
src := "debug"
sources := if src == "debug" { debug-sources } else { all-sources }

export TMPDIR := "/tmp"
#store-base := env("STORE_BASE_DIR", ".") # e.g. "/mnt/hdd1"

# Usage examples:
# just src=all pipeline
# just sources=glo30 pipeline
# just src=all TMPDIR=/mnt/hdd1/tmp pipeline
# Run pipeline (default: src=debug)
pipeline:
    @for src in "{{sources}}"; do \
        echo uv run python source_download.py $src; \
        uv run python source_download.py $src; \
    done

    {{ if sources =~ 'bewallonie' { "uv run python source_unzip.py bewallonie" } else { "" } }}

    {{ if sources =~ 'atsalzburg' { "uv run python source_set_crs.py atsalzburg EPSG:31258" } else { "" } }}

    {{ if sources =~ 'atkaernten' { "uv run python source_set_nodata.py atkaernten 0.0" } else { "" } }}
    {{ if sources =~ 'bewallonie' { "uv run python source_to_cog.py bewallonie" } else { "" } }}

    @for src in "{{sources}}"; do \
        echo uv run python source_bounds.py $src; \
        uv run python source_bounds.py $src; \
    done

    uv run python aggregation_covering.py
    uv run python downsampling_covering.py

    uv run python aggregation_run.py
    uv run python downsampling_run.py

    uv run python remove_dangling_pmtiles.py
    uv run python bundle.py 0.0.0
    uv run python download_urls.py 0.0.0
    uv run python attribution.py

# Run full pipeline
full:
    # uv run python source_download.py glo30
    # uv run python source_download.py swissalti3d
    # uv run python source_download.py at10
    # uv run python source_download.py atburgenland
    # uv run python source_download.py atoberoesterreich
    # uv run python source_download.py atsalzburg
    # uv run python source_download.py atkaernten
    # uv run python source_download.py beflanders
    # uv run python source_download.py bewallonie
    # uv run python source_download.py cz
    # uv run python source_download.py debayern
    # uv run python source_download.py deniedersachsen

    # uv run python source_unzip.py bewallonie
    # uv run python source_unzip.py cz

    # uv run python source_set_crs.py atsalzburg EPSG:31258

    # uv run python source_set_nodata.py atkaernten 0.0
    # uv run python source_to_cog.py bewallonie

    # uv run python source_bounds.py glo30
    # uv run python source_bounds.py swissalti3d
    # uv run python source_bounds.py at10
    # uv run python source_bounds.py atburgenland
    # uv run python source_bounds.py atoberoesterreich
    # uv run python source_bounds.py atsalzburg
    # uv run python source_bounds.py atkaernten
    # uv run python source_bounds.py beflanders
    # uv run python source_bounds.py bewallonie
    # uv run python source_bounds.py cz
    # uv run python source_bounds.py debayern
    # uv run python source_bounds.py niedersachsen

    # uv run python aggregation_covering.py
    # uv run python downsampling_covering.py

    # uv run python aggregation_run.py
    # uv run python downsampling_run.py
    # uv run python remove_dangling_pmtiles.py
    # uv run python create_index.py

    # TMPDIR=/tmp uv run python bundle.py 0.0.0
    # uv run python download_urls.py 0.0.0
    # uv run python attribution.py

# Reads AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY from .env
# Upload to cloudflare
upload:
    pmtiles upload bundle-store/planet/planet.pmtiles planet.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/6-33-21/6-33-21.pmtiles 6-33-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-33-22/6-33-22.pmtiles 6-33-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-21/6-34-21.pmtiles 6-34-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-34-22/6-34-22.pmtiles 6-34-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-21/6-35-21.pmtiles 6-35-21.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/6-35-22/6-35-22.pmtiles 6-35-22.pmtiles --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    pmtiles upload bundle-store/attribution.json attribution.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
    pmtiles upload bundle-store/download_urls.json download_urls.json --bucket="s3://mapterhorn?region=auto&endpoint=https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"
