"""Upload updated PMTiles bundles and source tarballs to object storage (R2/S3).

This module synchronizes local distribution artifacts to CDN-backed storage,
using MD5 checksums to avoid redundant uploads:

**Upload workflow**:
1. Download current download_urls.json and attribution.json from CDN
2. Compare local MD5 checksums against online versions
3. Upload only changed files:
   - PMTiles bundles: planet.pmtiles, regional 6-x-y.pmtiles
   - Source tarballs: {source}.tar.gz for attribution compliance
4. Update JSON manifests with new checksums and URLs

**Cloudflare R2 integration**:
- Uses AWS S3 CLI with custom endpoint (S3-compatible API)
- Requires AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY env vars
- Regional endpoint for low-latency uploads
- Public bucket with CDN caching for global distribution

**Incremental updates**:
The MD5 comparison enables efficient incremental deployments:
- After small source updates, only 1-2 regional bundles upload
- Planet bundle uploads only if z≤12 tiles changed
- Typical update: <1GB uploaded vs. ~50GB full sync

**Manifest synchronization**:
JSON files (download_urls.json, attribution.json) update atomically
after all referenced files upload successfully, ensuring clients never
see 404s for listed resources.

**Output**: Updated CDN content accessible at download.mapterhorn.com/
"""

import json

import requests

import utils

SILENT = False


def upload_local_resource_to_s3(directory, filename, bucket, key, region, endpoint):
    """Upload a local file to S3-compatible storage using aws cli."""
    """
    Requires the following env variables:
    $ export AWS_ACCESS_KEY_ID=MY_KEY
    $ export AWS_SECRET_ACCESS_KEY=MY_SECRET
    """
    command = f'aws s3 cp {directory}/{filename} s3://{bucket}/{key} --region {region} --endpoint "{endpoint}"'
    _, err = utils.run_command(command, silent=SILENT)
    if err != "":
        print("err:", err)
        raise Exception(err)


def handle_pmtiles(bucket, region, endpoint):
    """Upload PMTiles whose md5 differs from online download_urls.json.

    Sync algorithm:
    1. Fetch online download_urls.json via HTTPS GET
    2. Load local bundle-store/download_urls.json (generated by download_urls.py)
    3. Build map: online_items[name] = {url, md5sum, size, ...}
    4. For each local PMTiles:
       a. Check if name exists online AND md5sum matches
       b. If match: Skip (already uploaded, no changes)
       c. If new or changed:
          * Locate file in bundle-store/{name-without-extension}/{name}
          * Upload via aws s3 cp to bucket with same key as filename
    5. Errors halt upload (transactional: all-or-nothing for batch)

    The MD5 comparison is critical for efficiency: PMTiles bundles can be
    multi-GB, and unchanged bundles (e.g., Europe when only US data updated)
    skip upload entirely, saving hours of transfer time.

    Args:
        bucket: S3 bucket name (e.g., 'mapterhorn-downloads')
        region: AWS region (e.g., 'auto' for Cloudflare R2)
        endpoint: S3-compatible endpoint URL
    """
    r = requests.get("https://download.mapterhorn.com/download_urls.json")
    if r.status_code != 200:
        raise Exception("Error: could not get online download_urls.json")

    online_download_urls = json.loads(r.text)
    online_items = {}
    for item in online_download_urls["items"]:
        online_items[item["name"]] = item

    download_urls = None
    with open("bundle-store/download_urls.json") as f:
        download_urls = json.load(f)

    for item in download_urls["items"]:
        print(item["name"])
        if (
            item["name"] in online_items
            and online_items[item["name"]]["md5sum"] == item["md5sum"]
        ):
            print("Nothing changed. Skipping...")
            continue

        filename = item["name"]
        directory = f'bundle-store/{filename.replace(".pmtiles", "")}/'
        key = filename
        upload_local_resource_to_s3(directory, filename, bucket, key, region, endpoint)


def handle_tarballs(bucket, region, endpoint):
    """Upload source tarballs whose md5 differs from online attribution.json."""

    r = requests.get("https://download.mapterhorn.com/attribution.json")
    if r.status_code != 200:
        raise Exception("Error: could not get online attribution.json")

    online_attribution = json.loads(r.text)
    online_source_md5sums = {}
    for item in online_attribution:
        online_source_md5sums[item["source"]] = item["tarball_md5sum"]

    attribution = None
    with open("bundle-store/attribution.json") as f:
        attribution = json.load(f)

    for item in attribution:
        print(item["source"])
        if (
            item["source"] != "at1"
            and item["source"] in online_source_md5sums
            and online_source_md5sums[item["source"]] == item["tarball_md5sum"]
        ):
            print("Nothing changed. Skipping...")
            continue

        filename = f'{item["source"]}.tar'
        directory = "tar-store/"
        key = f"sources/{filename}"
        upload_local_resource_to_s3(directory, filename, bucket, key, region, endpoint)


if __name__ == "__main__":

    bucket = "mapterhorn"
    region = "auto"
    endpoint = "https://5521f1c60beed398e82b05eabc341142.r2.cloudflarestorage.com/"

    handle_pmtiles(bucket, region, endpoint)

    handle_tarballs(bucket, region, endpoint)
    exit()
    directory = "bundle-store/"

    filename = "attribution.json"
    key = filename
    upload_local_resource_to_s3(directory, filename, bucket, key, region, endpoint)

    filename = "download_urls.json"
    key = filename
    upload_local_resource_to_s3(directory, filename, bucket, key, region, endpoint)

    filename = "coverage.pmtiles"
    key = filename
    upload_local_resource_to_s3(directory, filename, bucket, key, region, endpoint)
