# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py remab
    uv run python source_to_cog.py remab
    uv run python source_to_egm2008.py remab
    uv run python source_bounds.py remab
    uv run python source_polygonize.py remab 32
    uv run python source_create_tarball.py remab
