# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py zzarcticdemb
    uv run python source_to_cog.py zzarcticdemb
    uv run python source_to_egm2008.py zzarcticdemb
    uv run python source_bounds.py zzarcticdemb
    uv run python source_polygonize.py zzarcticdemb 32
    uv run python source_create_tarball.py zzarcticdemb
