# BathDNN25 NetCDF -> sliced GeoTIFF prep
[no-cd]
default:
    uv run python source_download.py bathdnn
    uv run python source_bathdnn_convert.py bathdnn
    uv run python source_bounds.py bathdnn
    uv run python source_polygonize.py bathdnn 32
    uv run python source_create_tarball.py bathdnn
