# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py zzarcticdemg
    uv run python source_to_cog.py zzarcticdemg
    uv run python source_to_egm2008.py zzarcticdemg
    uv run python source_bounds.py zzarcticdemg
    uv run python source_polygonize.py zzarcticdemg 32
    uv run python source_create_tarball.py zzarcticdemg
