# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py ittrento
    uv run python source_bounds.py ittrento
    uv run python source_polygonize.py ittrento 32
    uv run python source_create_tarball.py ittrento
