[no-cd]
default:
    uv run python source_download.py itpiemonte
    uv run python source_unzip.py itpiemonte
    uv run python source_set_crs.py itpiemonte EPSG:32632
    uv run python source_set_nodata.py itpiemonte -99
    uv run python source_bounds.py itpiemonte
    uv run python source_polygonize.py itpiemonte 32
    uv run python source_create_tarball.py itpiemonte
