# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py remad
    uv run python source_to_cog.py remad
    uv run python source_to_egm2008.py remad
    uv run python source_bounds.py remad
    uv run python source_polygonize.py remad 32
    uv run python source_create_tarball.py remad
