[no-cd]
default:
    uv run python source_download.py cahrdem1
    uv run python source_slice.py cahrdem1 16384
    uv run python source_to_cog.py cahrdem1
    uv run python source_bounds.py cahrdem1
    uv run python source_polygonize.py cahrdem1 32
    uv run python source_create_tarball.py cahrdem1
