[no-cd]
default:
    uv run python source_download.py mx15m
    uv run python source_unzip.py mx15m
    uv run python source_bounds.py mx15m
    uv run python source_polygonize.py mx15m 32
    uv run python source_create_tarball.py mx15m
