[no-cd]
default:
    uv run python source_download.py ca
    uv run python source_slice.py ca 16384
    uv run python source_to_cog.py ca
    uv run python source_bounds.py ca
    uv run python source_polygonize.py ca 32
    uv run python source_create_tarball.py ca
