# Source preparation pipeline to be run from mapterhorn/pipelines folder

[no-cd]
default:
    uv run python source_download.py zzarcticdema
    uv run python source_to_cog.py zzarcticdema
    uv run python source_to_egm2008.py zzarcticdema
    uv run python source_bounds.py zzarcticdema
    uv run python source_polygonize.py zzarcticdema 32
    uv run python source_create_tarball.py zzarcticdema
