# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py nlahnhighres
    # fill holes with gdal_fillnodata.py
    uv run python source_fill_nodata.py nlahnhighres 1 100 2
    uv run python source_to_cog.py nlahnhighres
    uv run python source_bounds.py nlahnhighres
    # also fix compound CRS EPSG:28992
    uv run python source_polygonize.py nlahnhighres 32 EPSG:28992
    uv run python source_create_tarball.py nlahnhighres