name: source-aggregate-downsample

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/osgeo/gdal:ubuntu-small-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install
      
      - name: Download sources
        run: |
          uv run python source_download.py debug-glo30 
          uv run python source_download.py debug-swissalti3d
        working-directory: pipelines
