[no-cd]
default:
    uv run python source_download.py ca-hrdem-01m
    uv run python source_slice.py ca-hrdem-01m 16384
    uv run python source_to_cog.py ca-hrdem-01m
    uv run python source_bounds.py ca-hrdem-01m
    uv run python source_polygonize.py ca-hrdem-01m 32
    uv run python source_create_tarball.py ca-hrdem-01m
